ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT uuidv7();
ALTER TABLE "UserProfile" ALTER COLUMN "id" SET DEFAULT uuidv7();
ALTER TABLE "ProfileImage" ALTER COLUMN "id" SET DEFAULT uuidv7();
ALTER TABLE "Role" ALTER COLUMN "id" SET DEFAULT uuidv7();
ALTER TABLE "Video" ALTER COLUMN "id" SET DEFAULT uuidv7();
ALTER TABLE "Analysis" ALTER COLUMN "id" SET DEFAULT uuidv7();
